### ISSUE TITLE
Custom AX schema

### ISSUE THREAD

**Issue by clubdesarrolladores** [formapro/FpOpenIdBundle#82]
We are clients of a custom end point with this schema definition for AX attributes:

http://schema.custom.xxx.edu.ar/perfil
http://schema.custom.xxx.edu.ar/rol
http://schema.custom.xxx.edu.ar/legajo
http://schema.custom.xxx.edu.ar/escuela

How configure the required attributes for use this schemas?

```
fp_openid:
            create_user_if_not_exists: true
            provider: openid_user_manager
                - contact/email
                - namePerson/first
                - namePerson/last
                - pref/language
                - rol # this
                - perfil
                - legajo
                - escuela
```
