### ISSUE TITLE
[question] configuring the login

### ISSUE THREAD

**Issue by tchapi** [formapro/FpOpenIdBundle#85]
I'm using FpOpenIdBundle to allow my users to login via different services. Everything is pretty much working fine, and I have a login page at `/app/login` that does the job well for presenting the user with the different options.

My only problems is that any request to a page when the user is not logged is redirected to `/app/login_openid`, and I'd rather it redirects to `/app/login`. I've searched for a firewall option but to no avail. **Have you got any hints ?**

Here is my security configuration : 

```
firewalls:
    assets_and_dev:
        pattern:    ^/(_profiler|_wdt|css|js)
        security: false
    main:
        pattern:    ^/
        provider: user_db
        form_login:
            login_path: /app/login
            check_path: /app/login_check
            remember_me: true
        logout:
            path: /app/logout
            target: /app/
        security: true
        anonymous: ~
        fp_openid:
            provider: openid_user_manager
            login_path: /app/login_openid
            check_path: /app/login_check_openid
            create_user_if_not_exists: true 
            required_attributes:
                - contact/email
                - namePerson/first
                - namePerson/last
```

Thanks a lot for your help !

> NB : I'm using Symfony 2.3 but this should be the same as of 2.2 I suppose
